#!/bin/sh
apt install -y \
	build-essential \
	libx11-dev \
	libxft-dev \
	libxinerama-dev \
	libx11-xcb-deh \
	libxcb-res0-dev \
 	maim \
       	xclip \
	pavucontrol \
	firmware-linux \
	firmware-realtek \
	firmware-iwlwifi \
	meson \
	cmake \
	sudo \
	nodm \
	xorg \
	fuse \
	vim \
	libharfbuzz-dev \
	libpulse-dev \
	libboost1.74-all-dev 

usermod -aG sudo $(ls /home)
echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p


curl -s -L https://nvidia.github.io/nvidia-container-runtime/gpgkey | \
	  apt-key add -
	  distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
	  curl -s -L https://nvidia.github.io/nvidia-container-runtime/$distribution/nvidia-container-runtime.list | \
		    tee /etc/apt/sources.list.d/nvidia-container-runtime.list
	  apt-get update


(cd dwm && make clean install)
(cd dmenu && make clean install)
(cd dwmblocks && make clean install)
(cd st && make clean install)
(
  cp -r root/* / 
  sed s/NODM_USER=/NODM_USER=$(ls /home)/g -i /etc/default/nodm
)
(cd pamixer && meson setup build && meson compile -C build&& meson install -C build)
(
  git clone https://github.com/powerline/fonts.git --depth=1 
  cd fonts 
  ./install.sh 
  cd .. 
  rm -rf fonts
)

./clean
systemctl restart nodm
